// Crypto for temp rooms: a single shared AES-256-GCM key per room, generated by
// the host and carried in the URL fragment (never sent to any server — browsers
// never transmit fragments). Anyone with the full link can decrypt. This is a
// deliberately simpler, honestly-scoped trust model than the per-identity Olm
// Double Ratchet used for persisted 1:1/group chats (src/lib/crypto.ts) — no
// forward secrecy, no per-user identity, appropriate for a disposable room
// where the link itself is the access credential.

function toUrlSafeBase64(bytes: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function fromUrlSafeBase64(b64: string): Uint8Array {
  const padded = b64.replace(/-/g, '+').replace(/_/g, '/').padEnd(b64.length + ((4 - (b64.length % 4)) % 4), '=');
  const binary = atob(padded);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

export async function generateRoomKey(): Promise<CryptoKey> {
  return crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, true, ['encrypt', 'decrypt']);
}

export async function exportKeyToUrlSafe(key: CryptoKey): Promise<string> {
  const raw = await crypto.subtle.exportKey('raw', key);
  return toUrlSafeBase64(new Uint8Array(raw));
}

export async function importKeyFromUrlSafe(b64: string): Promise<CryptoKey> {
  const raw = fromUrlSafeBase64(b64);
  return crypto.subtle.importKey('raw', raw, { name: 'AES-GCM', length: 256 }, true, ['encrypt', 'decrypt']);
}

export async function encryptText(key: CryptoKey, text: string): Promise<{ iv: string; ciphertext: string }> {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const encoded = new TextEncoder().encode(text);
  const cipherBuf = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, encoded);
  return { iv: toUrlSafeBase64(iv), ciphertext: toUrlSafeBase64(new Uint8Array(cipherBuf)) };
}

export async function decryptText(key: CryptoKey, iv: string, ciphertext: string): Promise<string> {
  const ivBytes = fromUrlSafeBase64(iv);
  const cipherBytes = fromUrlSafeBase64(ciphertext);
  const plainBuf = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: ivBytes }, key, cipherBytes);
  return new TextDecoder().decode(plainBuf);
}
